spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.19/sell?characterEncoding=utf-8&useSSL=false
    jpa:
       show-sql: true
    jackson:
      default-property-inclusion: non_null
  resources:
    static-locations: classpath:/templates/,classpath:/static/
server:
  context-path: /sell
  port: 8080

#server:
#  servlet:
#    context-path: /sell
#logging:
#  pattern:
#    console: "%d-%msg"
#    path: /var/log/tomcat
#    file: /var/log/tomcat

wechat:
  mpAppId: wx29bc5201b9a80016
  mpAppSecret: 205a10aed8828750e04738cdbc1f91db
